create index campaign_scores_user_idx on public.campaign_scores (user_id);
create index files_uploaded_by_idx on public.files (uploaded_by);
create index incident_files_file_idx on public.incident_files (file_id);
create index pm_logs_schedule_idx on public.pm_logs (schedule_id);
create index pm_logs_technician_idx on public.pm_logs (technician_id);
create index pm_schedules_location_idx on public.pm_schedules (location_id);
create index point_transactions_incident_idx on public.point_transactions (ref_incident_id) where ref_incident_id is not null;
create index point_transactions_reward_item_idx on public.point_transactions (ref_reward_item_id) where ref_reward_item_id is not null;
create index profiles_approved_by_idx on public.profiles (approved_by) where approved_by is not null;
create index reward_items_image_file_idx on public.reward_items (image_file_id) where image_file_id is not null;
create index reward_redemptions_reward_item_idx on public.reward_redemptions (reward_item_id);
create index user_approval_history_user_idx on public.user_approval_history (user_id, created_at desc);
create index user_approval_history_acted_by_idx on public.user_approval_history (acted_by);
create index work_order_files_file_idx on public.work_order_files (file_id);
create index work_order_history_work_order_idx on public.work_order_history (work_order_id, changed_at desc);
create index work_order_history_changed_by_idx on public.work_order_history (changed_by) where changed_by is not null;

create policy api_only_managed_locations on public.managed_locations for all to authenticated using (false) with check (false);
create policy api_only_incidents on public.incidents for all to authenticated using (false) with check (false);
create policy api_only_files on public.files for all to authenticated using (false) with check (false);
create policy api_only_incident_files on public.incident_files for all to authenticated using (false) with check (false);
create policy api_only_sla_rules on public.sla_rules for all to authenticated using (false) with check (false);
create policy api_only_work_orders on public.work_orders for all to authenticated using (false) with check (false);
create policy api_only_work_order_history on public.work_order_history for all to authenticated using (false) with check (false);
create policy api_only_work_order_files on public.work_order_files for all to authenticated using (false) with check (false);
create policy api_only_pm_schedules on public.pm_schedules for all to authenticated using (false) with check (false);
create policy api_only_pm_logs on public.pm_logs for all to authenticated using (false) with check (false);
create policy api_only_point_wallets on public.point_wallets for all to authenticated using (false) with check (false);
create policy api_only_point_transactions on public.point_transactions for all to authenticated using (false) with check (false);
create policy api_only_reward_items on public.reward_items for all to authenticated using (false) with check (false);
create policy api_only_reward_redemptions on public.reward_redemptions for all to authenticated using (false) with check (false);
create policy api_only_reward_campaigns on public.reward_campaigns for all to authenticated using (false) with check (false);
create policy api_only_campaign_scores on public.campaign_scores for all to authenticated using (false) with check (false);
create policy api_only_user_approval_history on public.user_approval_history for all to authenticated using (false) with check (false);;
